### ISSUE TITLE
Document all class names

### ISSUE THREAD

**Issue by zebateira** [moxystudio/react-carousel#1]
It's really useful to see the classnames in the docs instead of having to poke around the devtools for the rendered dom to check this.

**Comment by jgradim** [comment]
There is a section that explains the rendered DOM structure with the default applied classes: https://github.com/moxystudio/react-carousel#html-structure

Is this what you meant?

**Comment by zebateira** [comment]
@jgradim ah that works yeah 👍 will close this.
